workflows:
  android-build:
    name: Android Build
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      node: 18
      java: 17
    scripts:
      - name: Install dependencies
        script: npm ci
      - name: Build Next.js
        script: npm run build
      - name: Sync Capacitor
        script: npx cap sync android
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
