workflows:
  android-build:
    name: Android Build
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      node: 18
      java: 17
      vars:
        NEXT_PUBLIC_SUPABASE_URL: "https://wiooeufthfytbflgtsnc.supabase.co"
        NEXT_PUBLIC_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indpb29ldWZ0aGZ5dGJmbGd0c25jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxOTI1NjQsImV4cCI6MjA3MDc2ODU2NH0.14ZbYsKHUgqZC6dZMhR_51Yf3F-mG_WRBpKO3cz_E7M"
    scripts:
      - name: Install dependencies
        script: npm ci
      - name: Build Next.js
        script: npm run build
      - name: Sync Capacitor
        script: npx cap sync android
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
